version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: repaircafedb
      MARIADB_USER: repaircafeuser
      MARIADB_PASSWORD: repaircafepassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
